import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import type { CreateAdminPayload } from "@/types";

export async function POST(request: Request) {
  // Verify requester is authenticated and is a super_admin
  const supabase = await createClient();
  const {
    data: { user: requester },
  } = await supabase.auth.getUser();

  if (!requester) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: requesterProfile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", requester.id)
    .single();

  if (requesterProfile?.role !== "super_admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const body: CreateAdminPayload = await request.json();
  const { email, password, full_name, phone, nationality, address, join_date } =
    body;

  if (!email || !password || !full_name) {
    return NextResponse.json(
      { error: "Missing required fields" },
      { status: 400 },
    );
  }

  // Step 1: Create the auth user.
  // The "on_auth_user_created" DB trigger automatically inserts a base
  // row into "profiles" (id, email, full_name, role) from this metadata.
  const { data: authData, error: authError } =
    await supabaseAdmin.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: { full_name, role: "admin" },
    });

  if (authError || !authData.user) {
    return NextResponse.json(
      { error: authError?.message ?? "Failed to create account" },
      { status: 400 },
    );
  }

  const newUserId = authData.user.id;

  // Step 2: Update the profile row with the remaining fields.
  const { error: profileError } = await supabaseAdmin
    .from("profiles")
    .update({
      phone: phone ?? null,
      nationality: nationality ?? null,
      address: address ?? null,
      must_change_password: true,
    })
    .eq("id", newUserId);

  if (profileError) {
    await supabaseAdmin.auth.admin.deleteUser(newUserId);
    return NextResponse.json({ error: profileError.message }, { status: 400 });
  }

  // Step 3: Create the admin row (admin_code is auto-generated by DB trigger)
  const { data: adminData, error: adminError } = await supabaseAdmin
    .from("admins")
    .insert({
      id: newUserId,
      join_date: join_date ?? null,
    })
    .select("admin_code")
    .single();

  if (adminError) {
    await supabaseAdmin.auth.admin.deleteUser(newUserId);
    return NextResponse.json({ error: adminError.message }, { status: 400 });
  }

  return NextResponse.json({
    admin: {
      id: newUserId,
      email,
      full_name,
      admin_code: adminData.admin_code,
    },
  });
}
