import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import type { CreateStudentPayload } from "@/types";

export async function POST(request: Request) {
  // Verify requester is authenticated and is an admin
  const supabase = await createClient();
  const {
    data: { user: requester },
  } = await supabase.auth.getUser();

  if (!requester) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: requesterProfile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", requester.id)
    .single();

  if (
    requesterProfile?.role !== "admin" &&
    requesterProfile?.role !== "super_admin"
  ) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const body: CreateStudentPayload = await request.json();
  const {
    email,
    password,
    full_name,
    department,
    academic_year,
    phone,
    nationality,
    address,
    date_of_birth,
    enrollment_date,
    expected_graduation,
    max_credits,
  } = body;

  if (!email || !password || !full_name || !department) {
    return NextResponse.json(
      { error: "Missing required fields" },
      { status: 400 },
    );
  }

  // Step 1: Create the auth user.
  // The "on_auth_user_created" DB trigger automatically inserts a base
  // row into "profiles" (id, email, full_name, role) from this metadata.
  const { data: authData, error: authError } =
    await supabaseAdmin.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: { full_name, role: "student" },
    });

  if (authError || !authData.user) {
    return NextResponse.json(
      { error: authError?.message ?? "Failed to create account" },
      { status: 400 },
    );
  }

  const newUserId = authData.user.id;

  // Step 2: Update the profile row with the remaining fields
  // (the base row already exists thanks to the trigger above).
  const { error: profileError } = await supabaseAdmin
    .from("profiles")
    .update({
      phone: phone ?? null,
      nationality: nationality ?? null,
      address: address ?? null,
      must_change_password: true,
    })
    .eq("id", newUserId);

  if (profileError) {
    // Rollback: remove the auth user (cascades to the trigger-created profile)
    await supabaseAdmin.auth.admin.deleteUser(newUserId);
    return NextResponse.json({ error: profileError.message }, { status: 400 });
  }

  // Step 3: Create the student row (student_code is auto-generated by DB trigger)
  const { data: studentData, error: studentError } = await supabaseAdmin
    .from("students")
    .insert({
      id: newUserId,
      department,
      academic_year: academic_year ?? null,
      date_of_birth: date_of_birth ?? null,
      enrollment_date: enrollment_date ?? null,
      expected_graduation: expected_graduation ?? null,
      max_credits: max_credits ?? 18,
    })
    .select("student_code")
    .single();

  if (studentError) {
    // Rollback: remove the auth user (cascades to profile if FK is ON DELETE CASCADE)
    await supabaseAdmin.auth.admin.deleteUser(newUserId);
    return NextResponse.json({ error: studentError.message }, { status: 400 });
  }

  return NextResponse.json({
    student: {
      id: newUserId,
      email,
      full_name,
      student_code: studentData.student_code,
    },
  });
}
