import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import type { CreateFacultyPayload } from "@/types";

export async function POST(request: Request) {
  // Verify requester is authenticated and is an admin
  const supabase = await createClient();
  const {
    data: { user: requester },
  } = await supabase.auth.getUser();

  if (!requester) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: requesterProfile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", requester.id)
    .single();

  if (
    requesterProfile?.role !== "admin" &&
    requesterProfile?.role !== "super_admin"
  ) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const body: CreateFacultyPayload = await request.json();
  const {
    email,
    password,
    full_name,
    department,
    phone,
    nationality,
    address,
    rank,
    employment_type,
    specialization,
    office_location,
    office_hours,
    join_date,
    max_courses,
    publications,
  } = body;

  if (!email || !password || !full_name || !department) {
    return NextResponse.json(
      { error: "Missing required fields" },
      { status: 400 },
    );
  }

  // Step 1: Create the auth user.
  const { data: authData, error: authError } =
    await supabaseAdmin.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: { full_name, role: "faculty" },
    });

  if (authError || !authData.user) {
    return NextResponse.json(
      { error: authError?.message ?? "Failed to create account" },
      { status: 400 },
    );
  }

  const newUserId = authData.user.id;

  // Step 2: Update the profile row with the remaining fields.
  const { error: profileError } = await supabaseAdmin
    .from("profiles")
    .update({
      phone: phone ?? null,
      nationality: nationality ?? null,
      address: address ?? null,
      must_change_password: true,
    })
    .eq("id", newUserId);

  if (profileError) {
    await supabaseAdmin.auth.admin.deleteUser(newUserId);
    return NextResponse.json({ error: profileError.message }, { status: 400 });
  }

  // Step 3: Create the faculty row (faculty_code is auto-generated by DB trigger)
  const { data: facultyData, error: facultyError } = await supabaseAdmin
    .from("faculty")
    .insert({
      id: newUserId,
      department,
      rank: rank ?? null,
      employment_type: employment_type ?? null,
      specialization: specialization ?? null,
      office_location: office_location ?? null,
      office_hours: office_hours ?? null,
      join_date: join_date ?? null,
      max_courses: max_courses ?? 4,
      publications: publications ?? 0,
    })
    .select("faculty_code")
    .single();

  if (facultyError) {
    await supabaseAdmin.auth.admin.deleteUser(newUserId);
    return NextResponse.json({ error: facultyError.message }, { status: 400 });
  }

  return NextResponse.json({
    faculty: {
      id: newUserId,
      email,
      full_name,
      faculty_code: facultyData.faculty_code,
    },
  });
}
