export * from './shared/auth'
export * from './shared/aside'
export * from './shared/statCard'
export * from './shared/fileSubmission'
export * from './shared/messages'
export * from './shared/notifications'
export type { Announcement } from './shared/announcements'
export * from './admin/dashboard'
export * from './admin/search'
export * from './student/dashboard'
export * from "./student/search";
export * from "./student/course";
export * from "./student/schedule";
export * from "./student/assignment";
export * from "./student/grades";
export * from "./student/profile";
export * from "./student/transcript";
export * from './faculty/dashboard'
export * from "./faculty/search";
export * from "./faculty/schedule";
export * from "./faculty/courses";
export * from "./faculty/attendance";
export * from "./faculty/submissions";
export * from "./faculty/student";
export * from "./faculty/profile";