export * from './shared/auth'
export * from './shared/aside'
export * from './shared/fileSubmission'
export * from './shared/messages'
export * from './admin/dashboard'
export * from './admin/search'
export * from './student/dashboard'
export * from "./student/search";
export * from "./student/course";
export * from "./student/schedule";
export * from "./student/assignment";
export * from './faculty/dashboard'
export * from "./faculty/search";