export * from './auth'
export * from './aside'
export * from './admin/dashboard'
export * from './admin/search'
export * from './student/dashboard'
export * from "./student/search";
export * from "./student/course";
export * from "./student/schedule";
export * from './faculty/dashboard'
export * from "./faculty/search";